### ISSUE TITLE
Beta Photo mode layout is broken on firefox

### ISSUE THREAD

**Issue by eMerzh** [mapillary/mapillary_issues#1032]
![capture d ecran 2015-05-28 a 15 20 05](https://cloud.githubusercontent.com/assets/177003/7860891/0a03cfb2-054d-11e5-97ce-7840f740af17.png)
did a force refresh 

firefox 38 on osx

**Comment by knikel** [comment]
@eMerzh Sorry about this, should be fixed now! Make sure to clear cache.

**Comment by de-vries** [comment]
still doesn't look perfect on my screen:
![mapillary crowdsourced street photos - mozilla firefox_060](https://cloud.githubusercontent.com/assets/1449609/7862321/5c959d16-0555-11e5-9c30-50b79fa04a96.png)

great work, btw on this beta!

**Comment by eMerzh** [comment]
yeah, much better for me :)
thanks for the reactivity :+1:

**Comment by knikel** [comment]
Awesome @eMerzh! I'll keep this issue one open until I fix what @de-vries mentioned. Hope that's OK?
