### ISSUE TITLE
Blurry images

### ISSUE THREAD

**Issue by Virtakuono** [mapillary/mapillary_issues#1139]
Accept my apologies if this bug report lands in the wrong place or is a duplicate of an already existing issue.

Using the iOS app I am having constant trouble with keeping the camera on focus. I guess it focuses on the nearest possible point or at the infinity at random times. The way to fix this is to go and open the camera app (the one that ships with the phone) and to tap on the screen so that the camera focuses again. After that I can reopen the mapillary app and it somehow "remembers" where my camera was focused in the camera app. Is there anything you can do to fix such behavior?

**Comment by jesolem** [comment]
Thanks for reporting!

This is the right place to file issues like this. We should fix this. 

I have seen this happen on long rides/drives where I come into an area with lots of blue sky in the field of view. 

Investigating.

**Comment by millenbop** [comment]
I'll add so that focus settings (AVCaptureAutoFocusRangeRestrictionFar) are updated more often instead of just once, hopefully that helps.

**Comment by canadarunner** [comment]
I already see, that this issue is closed, but with the newest version the problem isn't fixed! 
I would probose a "focus fix" option, that I can lock the focus point for the whole trip!

**Comment by Virtakuono** [comment]
Agreed, I had some trouble with the updated vesion too. (http://www.mapillary.com/map/im/yL8-5rZHoj-VBbJo2_SPxw/photo)

**Comment by Virtakuono** [comment]
Just as a bump, this is still very much an issue. Yesterday I did the following:
1. Start the app and start taking photos until the focus fails
2. Stop the car to give the camera a chance to focus, nothing happens
3. Switch to the native camera app to see if it focuses any better than the mapillary app. Within a second the image on the screen is sharp.
4. Switch back to mapillary, the image is still sharp, but only for a second, until the app messes it up again.

As for the app version, this is the test verson @millenbop sent me earlier...

**Comment by millenbop** [comment]
Thanks for reporting, I'll look into it again.

@canadarunner what device are you using?

**Comment by canadarunner** [comment]
I use an iPhone 6. iOS 9.2.1

Gruss Lorenz

**Comment by millenbop** [comment]
I have added so that when you set the exposure point by tapping on the screen, which should normally be the road, you now also set the focus point of interest. Should improve things when you have a lot of sky due to having to to tilting up the phone/camera to avoid car hood. It also resets the focus range restriction to far (`AVCaptureAutoFocusRangeRestrictionFar`). 

I hope this helps.

**Comment by millenbop** [comment]
Will be out in 4.1.6. Closing now, please reopen if problem persists.
