### ISSUE TITLE
Google Chrome says your page is in Portugeuse

### ISSUE THREAD

**Issue by domdomegg** [mapillary/mapillary_issues#1208]
Any map page (eg. http://www.mapillary.com/map/search/55.44529310002213/55.76529310002388/12.481965400467146/13.518347799689025) gives an option on Google Chrome (Mac, Stable, Version 44.0.2403.125 (64-bit)) to translate from Portugeuse. Guessing some rouge localisation tags somewhere?

**Comment by knikel** [comment]
@domdomegg This should be fixed, I've double checked the Content-Language, etc. But that's true, we have a list of possible languages you can choose from kept in the DOM, to this might confuse Chrome sometimes. I'll find a way to move the language list off the main navigation. Thanks for reporting @domdomegg!

**Comment by domdomegg** [comment]
Still have the same problem, even after clearing everything:
http://i.imgur.com/IwEMG8J.png

I've now reported it as a mistake to Google twice but still appears (first just before I posted this problem),  but still happens. There is an option to not try again for the site, so it doesn't matter much but just a little annoying to do for first time users, so is a weird bug.
