### ISSUE TITLE
Blur mode partially turned off

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#1228]
- open edit widget
- click on blur
 - blur buttons appear
- browse to the map view and back

result:
- The blur mode is partially turned off:
 - there are no blur buttons
 - the drag to move to next photo is enabled
 - edit widget is closed
- The blur mode is also partially turned on:
 - blurs are shown
 - it is possible to draw blurs
 - clicking blur doesn't show the blur buttons, but turns off blur mode

**Comment by knikel** [comment]
@de-vries, the default behavior should be that all overlays get turned off on the view change. This has been fixed now. Thank you!

**Comment by de-vries** [comment]
@knikel  I can still reproduce this bug by going to search view and back (using browser history)

**Comment by de-vries** [comment]
I can also reproduce this bug by going to the front page, my profile, manual uploads or settings and back. Clicking on other links like "how it works" or "blog" or bookmarks in my browser and going back leaves the blur feature enabled, which is fine to me.

**Comment by richlv** [comment]
seeing the same quite often. fairly annoying, as you might draw a blur or two, then notice that the button to request blurs is not there - re-enabling blur controls removes your manual blurs :/

**Comment by voschix** [comment]
I have a possibly related issue: 
In the past (up to a couple of weeks ago) I could walk through the photos of a sequence on the Mapillary site for editing either blurs or traffic signs by using the forward and backward arrows with either blur or traffic sign editing continuously enabled. 

This has recently been changed: 
the forward/backward arrows disappear when enabling either blur or traffic sign editing. 
As a consequence, in order to "walk" from one photo to the next for traffic sign editing, for every single photo in the sequence, I have to 
1. click the forward arrow
2. click traffic sign editing
3. verify that there are no false traffic signs (any picture can contain false traffic signs, and there are many of them)
4. do any traffic sign editing as necessary
5. unclick traffic sign editing

Then I have to do the same thing again for blurring, which in my case is necessary - I take photos on bicycle, where I "shoot" many close ups of faces, which then frequently escape the automatic blurring process of Mapillary.

Imagine a typical sequence of 500 or 1000 photos!

This is simply too time consuming to do, and as a consequence my photos are on the site without any checking/approving of traffic signs or blurs.

**Comment by richlv** [comment]
you might be able to use the keyboard arrows to navigate through the sequence - but it might be better to search for / create a new issue about that behaviour :)

**Comment by knikel** [comment]
Blurring will be improved in the upcoming update of mapillary.com. Will close this issue when we roll it out.
