### ISSUE TITLE
New viewer: Cannot blur up to the edge of a picture

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1290]
The new (and also the old) viewer doesn't allow to draw a blurring rectangle completely to one edge of a picture. One might want to do that for example when blurring a license plate that is not completely inside the picture. Allowing to draw a blurring rectangle over the edge of a picture (and by this blurring the image up to the edge) would allow for faster reviewing/blurring pictures.

**Comment by knikel** [comment]
This has been fixed with @paulinus and @oscarlorentzon blurring improvements!

**Comment by ltog** [comment]
@knikel : I just tested this with Firefox and Chrome on Windows 7. I still get the described behaviour. The behaviour of Firefox is especially ugly since the picture gets a blue color tone when moving the rectangle out of the picture. The picture seems to be marked/selected by the browser.

Please consider reopening the issue.

**Comment by knikel** [comment]
@ltog thanks for the feedback! I'll investigate that on FF/Chrome on Windows. Reopening

**Comment by oscarlorentzon** [comment]
Thanks for the feedback on this @ltog. 

It is now possible to blur to the edge of the image. When reaching the edge, the drawing will be stopped and the rectangle will be created. Please note that we rely on the mouse events so to make sure that the blur rectangle really reaches the edge the mouse movement should be fairly slow when approaching the edge. 

I have not made any changes regarding the "image selected with blue color tone" issue in firefox. If you feel this is a problem, please report a new issue.

**Comment by ltog** [comment]
@oscarlorentzon : It took me a while... :-) I reported a new issue (#1696) because of the picture with color tone thingy.
