### ISSUE TITLE
Several sequences keep the latlon of the first picture of the first sequence.

### ISSUE THREAD

**Issue by filipca** [mapillary/mapillary_issues#1741]
Samsung GS5
Android 5.0
mly 1.75
Google Play Services : on
Skip location check : off
Write trace logs : off
App GPS status running
No external GPS
I worked with my Ricoh Theta S those days.

Starting with this picture/sequence all following pictures in following sequences that day have that position.
https://www.mapillary.com/map/im/TQVJ4xRQ4rNqeeoMulN4SA/photo
variety.thin.steeped

This sequence from two days before also has the problem
https://www.mapillary.com/map/im/G5HVgXoJsUsBgem4WKzSAg/photo

The navigation between pictures is of course very wrong.
If there is no solution, you can delete my 1000+ flat pictures from march 8 2016 (after the spherical ones)

Now everything is OK

**Comment by ybkuang** [comment]
@rsahlin or @peterneubauer I checked the gps on the exifs, they look the same for all the photos. Can you check if this is related to the app?

**Comment by rsahlin** [comment]
Yes, it is probably an app issue.
Without any means of reproducing the issue it is very hard to know what has happened.
Let's keep the issue open and I will keep an eye out for the problem.

**Comment by paulinus** [comment]
Here's another example of the issue. Phone is a Nexus 5 in this case.
http://www.mapillary.com/map/im/gJtl4bGjP-mpyPyrig8uAg/photo

**Comment by rsahlin** [comment]
After discussing this with Peter we have come to the conclusion that a check will be added to skip capture if the current location is exactly the same as the last one (except for panorama mode)
Will look into this soon.

**Comment by polarbearing** [comment]
I had a similar issue where the speed was stuck to a value while standing, #1483. Not sure if that is still there in current versions, since I could not capture much in winter with lack of daylight.

**Comment by filipca** [comment]
Consecutive problem : I cannot hide the sequences.  Together with aberrations from another user, this leaves Brussels in a lamentable state.

**Comment by rsahlin** [comment]
Version 1.81 adds a check to skip capture if lat/lon is exactly the same as the last capture location.
It can be downloaded through http://www.mapillary.com/using.html - choose 'Direct Android .apk link'
 or through Google Play as a beta developer.
You can also wait a couple of days and it will be available as a regular release.

I'm not sure what can be done to salvage the already taken pictures, could @ybkuang or @paulinus perhaps be of assistance?

**Comment by filipca** [comment]
mly version 1.81, beta I think.
On a bicycle in "Walking auto shot".
I drive extra slowly on a roundabout to capture it well and i get the errror "Same place"
Panning to capture a crossroad while standing still would also be a problem.

I thought you would stop the capturing of images when 3 or more consecutive lat/lons are the same.  That would solve my problem and probably be no nuisance.

**Comment by rsahlin** [comment]
Yes, it turns out that Google Mobile Services are not very accurate and do not mandate that the accuracy is kept.
This means that when using GMS the location updates may be reported in the exact same location as previously.
Next version will default to GMS off (default GPS) and include an option to skip same location check.

Good point regarding panorama - will make sure the same location check is skipped for that.

**Comment by filipca** [comment]
Google Mobiles Services was OFF.

**Comment by rsahlin** [comment]
Thanks - I just found a thread access related issue.

Version 1.82 fixes acces to the location object from different threads (reading/writing).
Could you please try again with this version?
It should hopefully come through the Beta program soon :-)

Thanks for your support

**Comment by filipca** [comment]
I must also confess that the internal RAM of my smartphone was full.  I could not install more apps.  But my SD card is quick and has plenty of memory left.

OK I am in version 1.82 now and I will let it write trace logs.
I leave the "Skip same location check" unchecked.  (I do not like those double negatives, but here there is a reason for it.)

**Comment by filipca** [comment]
Version 1.82
No GMS
No Skip same location check
Walking auto shoot

Even at a speed of 15 km/h on a bike, I regularly get the message "Same location"

**Comment by rsahlin** [comment]
Thanks for reporting.

Means I have some more investigating to do before this one is solved :-|

**Comment by polarbearing** [comment]
It is the opposite for me. I still get the device to continue shooting at some (not all) red traffic lights.
Version 1.82
No GMS
No Skip same location check
Driving auto shoot

This was reported in #1483, and besides the non-zero speed value that is frozen to the same value in exactly all digits, the reported lat/lon location also has the same frozen value. So I was hoping the same-location-check would solve the problem, but it doesn't.
Log and exif dump available on request.

I guess the app reads some stale values from the location API. I have never seen e.g. OsmAnd reporting non-zero speed when standing.

**Comment by ybkuang** [comment]
This is an issue related to the app which should be fixed now. Please report back if you encounter similar issues.
