### ISSUE TITLE
Images skewed in v4.2.1 beta

### ISSUE THREAD

**Issue by talllguy** [mapillary/mapillary_issues#1790]
Note the skewed cars. Everything seems squished.
v4.2.1
iPhone 6s Plus

![2016-04-03 23 03 33](https://cloud.githubusercontent.com/assets/1827881/14251619/d817a802-fa51-11e5-92bd-9129155ca354.png)
![2016-04-03 23 03 18](https://cloud.githubusercontent.com/assets/1827881/14251621/d90f0110-fa51-11e5-962c-35e955462d24.png)

**Comment by millenbop** [comment]
Thanks for reporting!

Is it just this sequence or is it the same with all?

**Comment by talllguy** [comment]
Looks like it is all photos, all over. Maybe something with the dynamic
sizing?

On Mon, Apr 4, 2016 at 11:54 AM Anders Mårtensson <notifications@github.com>
wrote:

> Thanks for reporting!
>
> Is it just this sequence or is it the same with all?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mapillary/mapillary_issues/issues/1790#issuecomment-205363952>
>
-- 
Elliott Plack
http://elliottplack.me

**Comment by millenbop** [comment]
Looks like it's an "plus" issue! Works fine on smaller devices.

**Comment by millenbop** [comment]
Ok fixed now, will be out in a future release.

**Comment by talllguy** [comment]
Phablet problems :joy:

**Comment by talllguy** [comment]
@millenbop can we reopen this? Still an issue on the production version (which I just updated on the app store).


![img_0798](https://cloud.githubusercontent.com/assets/1827881/16746935/bec1f412-478a-11e6-84ad-eab831cd22d4.png)
![img_0797](https://cloud.githubusercontent.com/assets/1827881/16746936/becbf106-478a-11e6-84ce-2bf19da44178.png)

**Comment by millenbop** [comment]
Let's open this baby up! I'll promise to do more testing on plus sizes in the future!

**Comment by millenbop** [comment]
I just tried on both the simulator and on Kamil's iPhone 6 Plus and it's not stretched. I have a theory that you have an older version of the viewer cached (it's html/css/js so the browser likes to cache these things). 

It's not a solution to the problem/bug, but could you try deleting your app and installing it again? If it works then, it's a cache problem and I need to solve that somehow.

**Comment by talllguy** [comment]
I just deleted the app, and then reinstalled, but the issue is still there. I discovered a workaround of sorts, where if I go into fullscreen mode (portrait or landscape), and then back out, the skew is gone.

**Comment by millenbop** [comment]
Thanks! Hmm interesting, sounds like a race condition then. I'll investigate.

**Comment by millenbop** [comment]
Hopefully, this is now fixed, will be available in 4.2.3.

**Comment by millenbop** [comment]
@talllguy let me know if it works!

**Comment by talllguy** [comment]
@millenbop looks good on the 6s Plus! :tada:

**Comment by millenbop** [comment]
Yay, finally!
