### ISSUE TITLE
Video upload freeze at 100% - no upload

### ISSUE THREAD

**Issue by eugensim** [mapillary/mapillary_issues#2302]
Webupload 1.5+GB videos
Windows 10
Chrome last version 
Upload using https://legacy.mapillary.com/map/upload/vi

**Comment by gyllen** [comment]
@knikel Is this a known issue?

**Comment by ybkuang** [comment]
@gyllen @knikel This is the `classic` http v.s. https problem. http://legacy.mapillary.com/map/upload/vi generally solves the problem.

**Comment by gyllen** [comment]
@ybkuang I thought that one was solved...

@eugensim Can you try switching to http and see if that solve the upload problem?

**Comment by eugensim** [comment]
@gyllen it's ok now

**Comment by eugensim** [comment]
@gyllen @ybkuang @knikel Can you verify again? Only videos less than 1GB are working. I verified with http and also with https and the problem is back again.

**Comment by GITNE** [comment]
@ybkuang Is video upload even still working? When I choose my video file for upload the open file dialog just closes and nothing happens, regardless of HTTP or HTTPS. Here is my log:
```
GET
https://legacy.mapillary.com/map/upload/vi [HTTP/1.1 304 Not Modified 401ms]
GET
https://fonts.googleapis.com/css [HTTP/1.1 200 OK 263ms]
GET
https://apis.google.com/js/client.js [HTTP/1.1 304 Not Modified 631ms]
GET
https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.1/mapbox-gl.js [HTTP/1.1 304 Not Modified 630ms]
GET
https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.1/mapbox-gl.css [HTTP/1.1 304 Not Modified 586ms]
GET
https://js.stripe.com/v2/ [HTTP/1.1 304 Not Modified 262ms]
GET
https://js.arcgis.com/3.15/esri/css/esri.css [HTTP/1.1 200 OK 584ms]
GET
https://js.arcgis.com/3.15/dijit/themes/claro/claro.css [HTTP/1.1 200 OK 583ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/stylesheets/lib-d52c35c2.css [HTTP/1.1 304 Not Modified 648ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/stylesheets/mapapp-ce65dbf7.css [HTTP/1.1 304 Not Modified 659ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/javascripts/lib-44e3318d.js [HTTP/1.1 304 Not Modified 579ms]
GET
https://cdn.jsdelivr.net/leaflet.esri/1.0.0/esri-leaflet.js [HTTP/1.1 304 Not Modified 492ms]
GET
https://cdn.jsdelivr.net/leaflet.esri.renderers/1.0.1/esri-leaflet-renderers.js [HTTP/1.1 304 Not Modified 404ms]
GET
https://js.arcgis.com/3.15/ [HTTP/1.1 302 Moved Temporarily 646ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/javascripts/mapapp-5c590295.js [HTTP/1.1 304 Not Modified 582ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/javascripts/mapapp/config/routes-8d41aa6f.js [HTTP/1.1 304 Not Modified 645ms]
GET
https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_US.sNgbvR7KgdQ.O/m=client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCP4_U4lLpzYw74ZtGCfIQvvDOAJvA/cb=gapi.loaded_0 [HTTP/1.1 304 Not Modified 197ms]
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8248:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8256:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8264:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8272:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8280:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8288:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8296:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8304:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8312:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8320:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8328:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8336:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8344:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8352:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8360:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8368:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8376:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8384:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8392:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8400:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8408:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8416:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8424:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8432:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8440:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8448:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8456:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8464:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8472:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8480:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8488:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8496:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8504:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8512:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8520:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8528:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8536:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8544:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8552:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8560:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8568:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8576:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8584:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8592:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8600:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8608:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8616:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8624:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8632:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8640:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8648:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8656:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8664:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8672:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8680:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8688:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8696:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8704:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8712:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8720:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8728:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8736:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8744:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8752:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8760:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8768:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8776:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8784:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8792:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8800:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8808:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8816:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8824:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8832:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8840:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8848:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8856:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8864:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8872:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8880:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8888:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8896:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8904:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8912:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8920:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8928:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8936:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8944:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8952:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8960:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8968:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8976:10
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:8984:10
Error in parsing value for 'background-image'. Declaration dropped. mapapp-ce65dbf7.css:9204:20
Error in parsing value for 'background-image'. Declaration dropped. mapapp-ce65dbf7.css:9206:20
Expected end of value but found '1px'. Error in parsing value for 'text-shadow'. Declaration dropped. mapapp-ce65dbf7.css:9223:27
Unknown pseudo-class or pseudo-element '-webkit-scrollbar'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:9389:21
Unknown property 'user-drag'. Declaration dropped. mapapp-ce65dbf7.css:9454:11
Unknown property '-moz-border-radius'. Declaration dropped. mapapp-ce65dbf7.css:9527:22
Error in parsing value for 'cursor'. Declaration dropped. mapapp-ce65dbf7.css:9942:14
Unknown property '-moz-border-radius'. Declaration dropped. mapapp-ce65dbf7.css:10039:20
Error in parsing value for 'cursor'. Declaration dropped. mapapp-ce65dbf7.css:10375:10
Error in parsing value for 'cursor'. Declaration dropped. mapapp-ce65dbf7.css:10379:10
Error in parsing value for 'cursor'. Declaration dropped. mapapp-ce65dbf7.css:10401:14
Unknown property 'user-drag'. Declaration dropped. mapapp-ce65dbf7.css:10549:13
Unknown property '-moz-border-radius'. Declaration dropped. mapapp-ce65dbf7.css:10698:22
Error in parsing value for 'background-image'. Declaration dropped. mapapp-ce65dbf7.css:10762:22
Error in parsing value for 'background-image'. Declaration dropped. mapapp-ce65dbf7.css:10764:22
Unknown property '-moz-border-radius'. Declaration dropped. mapapp-ce65dbf7.css:10978:24
Unknown pseudo-class or pseudo-element 'selection'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:10985:27
Error in parsing value for 'cursor'. Declaration dropped. mapapp-ce65dbf7.css:11202:14
Error in parsing value for 'cursor'. Declaration dropped. mapapp-ce65dbf7.css:11209:14
Error in parsing value for 'background-image'. Declaration dropped. mapapp-ce65dbf7.css:11334:22
Error in parsing value for 'background-image'. Declaration dropped. mapapp-ce65dbf7.css:11336:22
Unknown property '-moz-background-size'. Declaration dropped. mapapp-ce65dbf7.css:11385:22
Unknown property '-moz-border-radius'. Declaration dropped. mapapp-ce65dbf7.css:11454:22
Unknown property '-moz-box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:11457:19
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:11708:12
Unknown property '-moz-border-radius'. Declaration dropped. mapapp-ce65dbf7.css:11713:22
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:11748:12
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:11760:12
Unknown property '-moz-border-radius'. Declaration dropped. mapapp-ce65dbf7.css:11765:22
Expected 'none', URL, or filter function but found 'progid'. Error in parsing value for 'filter'. Declaration dropped. mapapp-ce65dbf7.css:11800:12
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:12274:24
Unknown pseudo-class or pseudo-element 'read-only'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:12283:7
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:12294:24
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:12303:24
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:12315:24
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13165:11
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13166:11
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13167:11
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13264:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13265:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13266:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13271:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13272:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13273:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13278:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13279:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:13280:13
Error in parsing value for 'background-image'. Declaration dropped. mapapp-ce65dbf7.css:13734:20
Unknown pseudo-class or pseudo-element 'is-active'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14058:19
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14104:13
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14114:12
Unknown pseudo-class or pseudo-element 'placeholder'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14119:13
Unknown pseudo-class or pseudo-element 'read-only'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14131:12
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:14141:24
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:14149:24
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:14158:24
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14178:14
Unknown pseudo-class or pseudo-element '-webkit-slider-runnable-track'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14191:14
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14205:20
Unknown pseudo-class or pseudo-element '-webkit-progress-bar'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14234:11
Unknown pseudo-class or pseudo-element '-webkit-progress-value'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14239:11
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14395:14
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14407:14
Unknown pseudo-class or pseudo-element '-webkit-slider-runnable-track'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14428:14
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14446:20
Unknown pseudo-class or pseudo-element '-webkit-progress-bar'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14481:11
Unknown pseudo-class or pseudo-element '-webkit-progress-value'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:14486:11
Expected media feature name but found '-o-min-device-pixel-ratio'. mapapp-ce65dbf7.css:15370:48
Expected media feature name but found '-webkit-min-device-pixel-ratio'. mapapp-ce65dbf7.css:15370:86
Expected media feature name but found 'min-device-pixel-ratio'. mapapp-ce65dbf7.css:15370:125
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:15862:24
Unknown pseudo-class or pseudo-element 'read-only'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:15872:7
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:15885:24
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:15895:24
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:15911:24
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16761:11
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16762:11
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16763:11
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16860:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16861:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16862:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16867:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16868:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16869:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16874:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16875:13
Error in parsing value for 'display'. Declaration dropped. mapapp-ce65dbf7.css:16876:13
Error in parsing value for 'background-image'. Declaration dropped. mapapp-ce65dbf7.css:17330:20
Unknown pseudo-class or pseudo-element 'is-active'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17654:19
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17700:13
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17710:12
Unknown pseudo-class or pseudo-element 'placeholder'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17715:13
Unknown pseudo-class or pseudo-element 'read-only'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17727:12
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:17737:24
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:17745:24
Expected end of value but found 'color('. Error in parsing value for 'box-shadow'. Declaration dropped. mapapp-ce65dbf7.css:17754:24
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17774:14
Unknown pseudo-class or pseudo-element '-webkit-slider-runnable-track'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17787:14
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17801:20
Unknown pseudo-class or pseudo-element '-webkit-progress-bar'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17830:11
Unknown pseudo-class or pseudo-element '-webkit-progress-value'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17835:11
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:17991:14
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:18003:14
Unknown pseudo-class or pseudo-element '-webkit-slider-runnable-track'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:18024:14
Unknown pseudo-class or pseudo-element '-webkit-slider-thumb'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:18042:20
Unknown pseudo-class or pseudo-element '-webkit-progress-bar'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:18077:11
Unknown pseudo-class or pseudo-element '-webkit-progress-value'. Ruleset ignored due to bad selector. mapapp-ce65dbf7.css:18082:11
GET
https://js.arcgis.com/3.15/init.js [HTTP/1.1 200 OK 923ms]
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead lib-44e3318d.js:16745:0
GET
https://accounts.google.com/o/oauth2/postmessageRelay [HTTP/1.1 200 OK 0ms]
GET
https://ssl.gstatic.com/accounts/o/1240234406-postmessagerelay.js [HTTP/1.1 200 OK 0ms]
GET
https://apis.google.com/js/rpc:shindig_random.js [HTTP/1.1 200 OK 0ms]
GET
https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_US.sNgbvR7KgdQ.O/m=rpc,shindig_random/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCP4_U4lLpzYw74ZtGCfIQvvDOAJvA/cb=gapi.loaded_0 [HTTP/1.1 200 OK 0ms]
_ _ _ _ _ mapapp-5c590295.js:3:3
' ) ) ) // // mapapp-5c590295.js:5:3
/ / / __. _ o // // __. __ __ , mapapp-5c590295.js:7:3
/ ' (_(_/|_/_)_<_</_</_(_/|_/ (_/ (_/_ mapapp-5c590295.js:9:3
/ / mapapp-5c590295.js:11:3
' ' mapapp-5c590295.js:13:3
You are quite a hacker (1337) mapapp-5c590295.js:15:3
"File bugs at https://github.com/mapillary/mapillary_issues" mapapp-5c590295.js:17:3
"or get a job at http://www.mapillary.com/jobs" mapapp-5c590295.js:19:3
TypeError: a is undefined 3.15:49:376
unreachable code after return statement mapapp-5c590295.js:6307:8
unreachable code after return statement mapapp-5c590295.js:17349:14
unreachable code after return statement mapapp-5c590295.js:18278:12
unreachable code after return statement mapapp-5c590295.js:30238:8
unreachable code after return statement mapapp-5c590295.js:30252:8
GET
https://www.google-analytics.com/analytics.js [0ms]
GET
https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js [0ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/img/store-img/app-store.png [HTTP/1.1 304 Not Modified 234ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/img/store-img/play-store.png [HTTP/1.1 304 Not Modified 550ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/img/store-img/amazon-store.png [HTTP/1.1 304 Not Modified 424ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/img/store-img/windows-store.png [HTTP/1.1 304 Not Modified 423ms]
GET
https://d3m3mygpr8qr0q.cloudfront.net/img/mapillary-logo-white.png [HTTP/1.1 304 Not Modified 565ms]
GET
https://js.stripe.com/v2/channel.html [HTTP/1.1 200 OK 451ms]
OPTIONS
XHR
https://a.mapillary.com/v2/me [HTTP/1.1 200 OK 507ms]
GET
XHR
https://legacy.mapillary.com/templates/directives/mapillarynavlinks.html [HTTP/1.1 304 Not Modified 120ms]
GET
XHR
https://legacy.mapillary.com/templates/directives/languagePicker.html [HTTP/1.1 304 Not Modified 263ms]
GET
XHR
https://legacy.mapillary.com/templates/views/upload/vi.html [HTTP/1.1 304 Not Modified 363ms]
GET
https://browser-update.org/update.js [HTTP/1.1 403 Forbidden 364ms]
GET
https://js.stripe.com/v2/ [HTTP/1.1 200 OK 0ms]
GET
XHR
https://a.mapillary.com/v2/me [HTTP/1.1 304 Not Modified 353ms]
GET
https://legacy.mapillary.com/img/upload-successful.png [HTTP/1.1 304 Not Modified 123ms]
GET
XHR
https://legacy.mapillary.com/templates/directives/mapillarymap.html [HTTP/1.1 200 OK 0ms]
OPTIONS
XHR
https://a.mapillary.com/v2/me/uploads/secrets [HTTP/1.1 200 OK 337ms]
OPTIONS
XHR
https://a.mapillary.com/v2/me/uploads/status [HTTP/1.1 200 OK 574ms]
unreachable code after return statement mapapp-5c590295.js:18278:12
GET
https://legacy.mapillary.com/img/north-arrow.png [HTTP/1.1 304 Not Modified 155ms]
GET
XHR
https://legacy.mapillary.com/templates/directives/mapesritoggle.html [HTTP/1.1 200 OK 0ms]
GET
https://a.tiles.mapbox.com/v3/mapillary.i5ce5362/0/0/0.png [HTTP/1.1 304 Not Modified 159ms]
GET
XHR
https://a.mapillary.com/v2/me/uploads/secrets [HTTP/1.1 304 Not Modified 340ms]
GET
XHR
https://a.mapillary.com/v2/me/uploads/status [HTTP/1.1 304 Not Modified 408ms]
Use of getPreventDefault() is deprecated. Use defaultPrevented instead. lib-44e3318d.js:16750:0
```

**Comment by eugensim** [comment]
@GITNE is not working for me too

**Comment by ybkuang** [comment]
@GITNE @eugensim Thanks for reporting. @gyllen can you help and take a look here?

**Comment by eugensim** [comment]
@gyllen please look again at the video max size. It should be 5GB but, it doesn't work even with less than 800MB.

**Comment by eugensim** [comment]
@gyllen please look again at the video max size. It should be 5GB but, it doesn't work even with less than 800MB.

**Comment by gyllen** [comment]
@katrin I want to elevate this as an internal bug, guide me through what I should do

**Comment by knikel** [comment]
mapillary_issues is no longer an active repository.

This issue has been moved over to our internal task list. Please send an email to support@mapillary.com with a reference to this issue if you want to add more information, or want to be notified once it’s been fixed!
