### ISSUE TITLE
Mapillary 3.55 doesn't upload

### ISSUE THREAD

**Issue by ArAge67** [mapillary/mapillary_issues#2562]
### Basic information
* Platform: `Android 4.1.2`
* Version: `app version 3.55...` 
* System/Browser: `...`

### Expected behavior

Upload sequence

### Actual behavior

Doesn't upload

### Additional information

See attached log file 

[mapillary.log.txt](https://github.com/mapillary/mapillary_issues/files/984508/mapillary.log.txt)

**Comment by jfburke3** [comment]
Were the sequences taken with version 3.55, or a previous one?  Also, what phone are you using?

**Comment by ArAge67** [comment]
Don't know for sure, photos were taken on May 5th, Mapillary was updated May 5th  :-). Maybe the log has more info? Device is a Samsung Galaxy S2 see also mapillary.log snippet:

19:43:52.050 D/app.mapillary.android.activity.TabbedMainActivity(21868): *********** Phone Info ***********
05-08 19:43:52.050 D/app.mapillary.android.activity.TabbedMainActivity(21868): Mapillary versionName       : 3.55
05-08 19:43:52.050 D/app.mapillary.android.activity.TabbedMainActivity(21868): Mapillary versionCode       : 355
05-08 19:43:52.050 D/app.mapillary.android.activity.TabbedMainActivity(21868): Android name                : REL
05-08 19:43:52.050 D/app.mapillary.android.activity.TabbedMainActivity(21868): Android version             : 16
05-08 19:43:52.050 D/app.mapillary.android.activity.TabbedMainActivity(21868): Android device              : GT-I9100
05-08 19:43:52.050 D/app.mapillary.android.activity.TabbedMainActivity(21868): Android device model        : GT-I9100
05-08 19:43:52.050 D/app.mapillary.android.activity.TabbedMainActivity(21868): Android device manufacturer : samsung
05-08 19:43:52.050

**Comment by katrinhumal** [comment]
@ArAge67 Thanks for reporting! We need to sort this out asap. Very helpful of you to send logs - could you just describe in a bit more detail the "actual behaviour" and what you see happening when you try to upload?

**Comment by ArAge67** [comment]
@katrinhumal I made a few screenshots when I tried to upload a sequence:

![screenshot_2017-05-09-13-15-13](https://cloud.githubusercontent.com/assets/12451224/25848489/ee831492-34ba-11e7-82c7-f6f910c361a1.png)
![screenshot_2017-05-09-13-15-31](https://cloud.githubusercontent.com/assets/12451224/25848491/ee84d462-34ba-11e7-9975-6ef9c17a1a67.png)
![screenshot_2017-05-09-13-15-43](https://cloud.githubusercontent.com/assets/12451224/25848492/ee852a0c-34ba-11e7-8f85-1eb34b6da7ca.png)
![screenshot_2017-05-09-13-15-48](https://cloud.githubusercontent.com/assets/12451224/25848490/ee8336c0-34ba-11e7-9038-c7bb905c0b19.png)
![screenshot_2017-05-09-13-16-12](https://cloud.githubusercontent.com/assets/12451224/25848493/ee85c7be-34ba-11e7-90ff-26762d36d9c7.png)

**Comment by peterneubauer** [comment]
New version coming out soon. Meanwhile, can you please test http://android-releases.mapillary.io/Mapillary_Android_3.56-SNAPSHOT2.apk and let us know if that works better?

**Comment by vincentdephily** [comment]
I'm affected by the same problem on 3.55 for photos taken on the 5th, and only tried to diagnose now. The snapshot version managed to upload my two sequences, thanks :)

On the other hand, the end-of-upload message is a bit worrysome: it only tells me about one sequence having been uploaded, and it offers me to cancel... My already-uploaded sequence ? It'd be nice to have the list of sequences (not just the latest one) and to s/cancel/ok/.
![screenshot_20170510-181331](https://cloud.githubusercontent.com/assets/115401/25911726/2ec7bb84-35b5-11e7-968a-a432d0dccb53.png)

**Comment by ArAge67** [comment]
Tried your Mapillary_Android_3.56-SNAPSHOT2.apk today but still no upload of photos. This is what the upload tab shows:

![screenshot_2017-05-10-21-06-38](https://cloud.githubusercontent.com/assets/12451224/25918241/090694e0-35cb-11e7-8292-5d2652253631.png)

After that nothing happens. So I tried a device reboot, pressed upload again and got this:

![screenshot_2017-05-10-21-06-56](https://cloud.githubusercontent.com/assets/12451224/25918328/55564106-35cb-11e7-912f-c4db74641a3c.png)

Waited a while but again nothing happened. Now every time I restart Mapillary the first screenshot is shown in the upload section.
Maybe the new log file tells you more about what's wrong: 
[mapillary.log.txt](https://github.com/mapillary/mapillary_issues/files/991078/mapillary.log.txt)

**Comment by ovivoda** [comment]
@ArAge67 From logs it seems that there are some corrupted JPG files in the sequence. 
Please try http://android-releases.mapillary.io/Mapillary_Android_3.57-SNAPSHOT3.apk .
This version will just skip corrupted JPG files and upload the all others. You will see a detailed report in the sequence card when the upload is complete.

Let me know if it works better. Tx!

**Comment by ArAge67** [comment]
@ovivoda Much better! Discovered three issues though: 

1. Mapillary_Android_3.57-SNAPSHOT3.apk uploaded almost all my photos except one. This photo seems to be corrupted according to the standard Android picture viewer. Should Mapillary delete this photo automatically? Mapillary now keeps showing this:
![screenshot_2017-05-23-21-04-10](https://cloud.githubusercontent.com/assets/12451224/26373172/cb30d550-4000-11e7-9e57-eb35fca4c5c1.png)

or this info screen:
![screenshot_2017-05-23-21-09-40](https://cloud.githubusercontent.com/assets/12451224/26373188/da14a128-4000-11e7-91bb-742004f4fecf.png)





2. While uploading Mapillary crashed:
![screenshot_2017-05-22-21-36-34](https://cloud.githubusercontent.com/assets/12451224/26373136/ac41d04a-4000-11e7-82ee-fc81bb656289.png)

Maybe you can find the cause in the log file I created right after the crash: 
[mapillary.log.txt](https://github.com/mapillary/mapillary_issues/files/1023493/mapillary.log.txt)

3. The trace on the web shows an odd jump. Look at this photo https://www.mapillary.com/map/im/hT7f2dX2btsE3CnqA6B9xA which jumps to the beginning of the sequence. Instead it should be connected to the follow up photo https://www.mapillary.com/map/im/4RFj5nVt7PMgZo26IVJwWQ.

**Comment by ovivoda** [comment]
@ArAge67 Thanks for your feedback.

Please see my comments:

1. Mapillary will not delete the image but it should mark it as a stray image. Can you please send the image to us so we can check why it does not see it as a stray image? So instead of "one more photo to upload" it should say "one stray photo, ignored"
I will work on the dialog UX as it seems that CANCEL button is cut off.

2. I fixed the crash. Can you try this version here please: http://android-releases.mapillary.io/Mapillary_Android_v3.58-SNAPSHOT2.apk

3. Please use http://android-releases.mapillary.io/Mapillary_Android_v3.58-SNAPSHOT2.apk and send us the logs when you will see a jumped image. We added some more logs in there to help us figure out what's wrong

**Comment by ArAge67** [comment]
@ovivoda Thanks for your support. 

This is the jpg file you were asking for: 
![2017_05_05_13_06_28_846](https://cloud.githubusercontent.com/assets/12451224/26463462/abd0b48e-4184-11e7-8514-6d356427b201.jpg)
Do I have to delete this file manually or should I leave it there to test future Mapillary versions?

FYI I installed Mapillary_Android_v3.58-SNAPSHOT2.apk but noticed a different software version (snapshot1):

![screenshot_2017-05-25-20-19-42](https://cloud.githubusercontent.com/assets/12451224/26464872/89e720f6-4189-11e7-9ef1-e3dd62e59eba.png)

**Comment by ArAge67** [comment]
@ovivoda Today I noticed that the traces shot with Mapillary_Android_v3.58-SNAPSHOT2.apk show a lot of jumps or cutoff sequences. All my photos/sequences taken on May 27th have these problems. And I'm sorry to say but I don't have a log file of the 27th available but only of May 29th: 
[mapillary.log.txt](https://github.com/mapillary/mapillary_issues/files/1045885/mapillary.log.txt) but maybe it's still ok for you to figure out what's wrong.

Please take a look at this sequence for example: https://www.mapillary.com/map/im/5Vwpki0kv2vsO82kcH7ZDg. It jumps all over the place. Or look at this one which is cutoff https://www.mapillary.com/map/im/SqPVRzykzrODVqZbW78YSA. Only a small part is visible on the website where it should contain 239 photos according to the webpage:
![cutoff sequence](https://cloud.githubusercontent.com/assets/12451224/26698874/e1fa99d8-4717-11e7-9380-47e8dbdc98be.PNG)

**Comment by peterneubauer** [comment]
Hi there,
This can be a backend issue, since the generated tiles lag currently some
day - we are regenerating a lot of them. Yiu should be able just to wait a
few days until we catch up. Otherwise, please let me know.

On Jun 1, 2017 10:20 PM, "ArAge67" <notifications@github.com> wrote:

@ovivoda <https://github.com/ovivoda> Today I noticed that the traces shot
with Mapillary_Android_v3.58-SNAPSHOT2.apk show a lot of jumps or cutoff
sequences. All my photos/sequences taken on May 27th have these problems.
And I'm sorry to say but I don't have a log file of the 27th available but
only of May 29th:
mapillary.log.txt
<https://github.com/mapillary/mapillary_issues/files/1045885/mapillary.log.txt>
but maybe it's still ok for you to figure out what's wrong.

Please take a look at this sequence for example:
https://www.mapillary.com/map/im/5Vwpki0kv2vsO82kcH7ZDg. It jumps all over
the place. Or look at this one which is cutoff
https://www.mapillary.com/map/im/SqPVRzykzrODVqZbW78YSA. Only a small part
is visible on the website where it should contain 239 photos according to
the webpage:
[image: cutoff sequence]
<https://cloud.githubusercontent.com/assets/12451224/26698874/e1fa99d8-4717-11e7-9380-47e8dbdc98be.PNG>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/mapillary/mapillary_issues/issues/2562#issuecomment-305608869>,
or mute the thread

**Comment by simonpoole** [comment]
3.59 app refuses to upload 2/3 of a sequence, nothing obviously wrong with the images. Wit:
![screenshot_2017-06-09-23-58-38](https://user-images.githubusercontent.com/1011860/26996151-057c14fe-4d71-11e7-9ee4-3520e0ccbe57.png)
![screenshot_2017-06-09-23-59-00](https://user-images.githubusercontent.com/1011860/26996161-10c2a1a2-4d71-11e7-9b47-11af999a364d.png)

Log files sent.

**Comment by simonpoole** [comment]
I now have 2 further sequences (with > 1000 images) that are showing issues, https://github.com/mapillary/mapillary_issues/issues/2596 would seem to indicate that currently the android app cannot be used. Or does have mapillary have a work around or other suggestion?

**Comment by ovivoda** [comment]
Hi Simon

Please try this APK and let me know if it works:
Mapillary_Android_3.60-SNAPSHOT2_orig_images.apk
<http://android-releases.mapillary.io/Mapillary_Android_3.60-SNAPSHOT2_orig_images.apk>

We fixed some upload issues related to stray images.

Thanks!

Ovidiu

**Comment by simonpoole** [comment]
@ovivoda looks good, I was even able to upload a few stuck images from two three weeks back, besides those that currently weren't uploading.

**Comment by ArAge67** [comment]
@peterneubauer Waited a few weeks but regeneration didn't fix the sequence see attached picture:
![239_photos](https://user-images.githubusercontent.com/12451224/27511183-1a629f8c-591f-11e7-9e69-016786084d7b.PNG)

**Comment by ovivoda** [comment]
Please try v3.67 or v3.70-BETA from GooglePlay and let us know if you can still see same behavior
