### ISSUE TITLE
Nearly 5000 "stray photos" in one day

### ISSUE THREAD

**Issue by gappleto97** [mapillary/mapillary_issues#2621]
What is a stray photo?

How can I recover these sequences? Can I provide logs of some sort to help? 

Android 7.1.1, Nexus 6P

**Comment by echeloni2p** [comment]
Which version?
tracelog available?
GPS did work?

**Comment by gappleto97** [comment]
GPS did work

Version 3.65

Log here: http://www62.zippyshare.com/v/x0PyLxXv/file.html

Looks like it only covered the most recent opening of the app though. I would point out that the camera was operating continuously, and that these were mixed in with ~3000 non-stray images.

**Comment by katrinhumal** [comment]
Hi @gappleto97 - thanks for reporting. We discovered a bug due to which GPS was missing after the first sequence. A fix has been released with version 3.67, please test if possible and let us know if this has resolved your issue?

For those photos already taken, I'm afraid there is no way to recover since the GPS was not recorded. It sounds like way too many images to fix manually...

**Comment by gappleto97** [comment]
Did not resolve. Every sequence not started manually was entirely stray images. This is while OsmAnd was still able to get location in the background. Definitely not the device.

**Comment by katrinhumal** [comment]
@gappleto97 thank you for testing and letting us know! Handing this over to our developers.

**Comment by gubuntu** [comment]
Same thing with me, I have hundreds of stray images from many sequences over the past few weeks. An upload will start but then there will be network or I/o error that interrupts it, then when I restart the upload, all remaining images are stray. When they were taken the GPS was good.

**Comment by dmbreaker** [comment]
Still have stray photos. It's a bug in the app. I uploaded small part of images, everything gone ok, then cancelled further upload (expected lost of WiFi).
Just tried to continue but all images became strayed.
It's a waste of time.
Have to stop making new photos until the issue fixed.

**Comment by ovivoda** [comment]
@gappleto97 @gubuntu @dmbreaker Can you please send us the sequences with stray images over?

**Comment by Robot8A** [comment]
Same, 8600 photos in 33 sequences, all strayed. When I try to upload them, it skips them.

**Comment by gappleto97** [comment]
I already deleted, as I was told to above

**Comment by gubuntu** [comment]
Hi @ovivoda what's the path to the sequences (Android) and how or where should I send them?

**Comment by ovivoda** [comment]
@gubuntu You can check in the left hamburger navigation menu and go to Settings->Storage->See location under "Picture storage location".

You can just grab the images using Android File Transfer and upload them somewhere and just send the link to me. 

Another thing that you can try first is to set your device time zone to the time zone used when you took the pictures. This is the main cause for stray images lately and we are working on fixing that as we speak.

**Comment by dmbreaker** [comment]
https://yadi.sk/d/KrS4SoN-3LPU9a
Example of strayed images

**Comment by gappleto97** [comment]
Can we assume this is high priority for you guys? I feel like I can't use your service until its fixed. Especially since I already lost 6 hours of driving to this bug.

**Comment by ulikoehler** [comment]
Maybe related to the conversion at  https://github.com/mapillary/mapillary_issues/issues/2634 ? (probably not related to the bug itself).

I was able to test with the 3.73 Snapshot today, albeit only with ~200 images, and no stray images were produced.

Maybe you guys can check the snapshot, too? http://android-releases.mapillary.io/Mapillary_Android_3.73-SNAPSHOT1.apk

**Comment by gubuntu** [comment]
I set time zones for my stray sequences and they've all uploaded successfully!

**Comment by katrinhumal** [comment]
@gappleto97 Yes, you can assume that. We're actively working on this.

**Comment by voschix** [comment]
I have regularly stray photos, often more than 200 in a 600-image sequence. Time zones are not involved. All local photos. They normally upload OK on the second go. Would be nice to get rid of this problem, as this require additional manual work.
Android App 3.67 on a Sony Xperia Z5 compact.

**Comment by dmbreaker** [comment]
I confirm workaround with temporary timezone change.

**Comment by gappleto97** [comment]
Oh man, what if this is because of a time zone change while recording? I crossed from Eastern to Central and back while recording the traces I got stales in. If adding a time zone fixed things, that makes me think this might be relevant.

**Comment by ovivoda** [comment]
@voschix Please try the beta version on GooglePlay and let me know if that one works better.

**Comment by ulikoehler** [comment]
Since at least the last beta version from Google Play I've not encountered the stray image issue any more on Android. It would be great it someone could cross-check this.

**Comment by jaakkoh** [comment]
Hmm. I took about 76 thousand photos driving 8000+ km across Europe in July and first had problems with my first batch (SD card full) of 21k or so photos. I think I had some stray photos but didn't pay attention that much as (I think that) they eventually uploaded ok.

I then copied back to the SD card another batch of around 30k photos and these are all failing to upload due to the stray photo error.

I know that my mapillarying wasn't perfect on this trip. With family on board etc vacation stuff I missed the fact that my phone date-time was some 4 days off for a part of the trip. (I haven't investigated if these photos are impacted by that.) But the GPS was on and recording ok (at least seemingly). The LEGACY_CAM_0_*.gpx exists in the folders in question.

I don't have time to investigate this this week but am of course bummed (to say the least!) if the result will end up being that the photos can't be uploaded.

I [uploaded the trace](https://www.dropbox.com/s/p4jzddv3qjr2enn/mapillary_trace.txt?dl=0) that covers the full trip (June 26 to August 6). The upload problems of SD card full of photos skipped as stray photos is from the past few days (including today just before posting this now.)

(Phone: Galaxy S5, Mapillary version: not sure what it was when I took the photos.)

**Comment by gappleto97** [comment]
I managed to get ~40 hours of driving recorded using the new version. None of these ended up being strays. I'm pretty sure this issue can now be closed.

**Comment by ovivoda** [comment]
@gappleto97 Thanks for letting us know!

**Comment by ovivoda** [comment]
@jaakkoh Have you managed to upload the sequences? We have new versions out. You can try our latest version in beta channel.

**Comment by jaakkoh** [comment]
@ovivoda I'll give it a try. I gather that the new version should also be able to handle the photos taken with the versions that had the stray photos problem?

**Comment by katrinhumal** [comment]
@jaakkoh That's what we hope!

**Comment by jaakkoh** [comment]
Ok. It seems like the newest beta is working in regards to upload. And it was able to also get the photos taken with previous problematic version(s?) uploaded so that they show on the map.

**Comment by katrinhumal** [comment]
@jaakkoh YAY! I hope this stays that way. Keep us posted.
