### ISSUE TITLE
Stop not working without GPS on iOS

### ISSUE THREAD

**Issue by Andblue** [mapillary/mapillary_issues#296]
I could not stop a sequence when the phone did not have GPS reception. Using the updated app on iPhone. Tapping the red button and the app responded with a message. I was driving so I could not read the message.

Not a huge issue and I don't know if this was a one time thing or not.

**Comment by jesolem** [comment]
This should be fixed. @Andblue ?

**Comment by Andblue** [comment]
@jesolem I haven't run into the problem lately, but I haven't been in such a situation, so I can't really tell.

I will give it a try tomorrow.

**Comment by Andblue** [comment]
Test done.

1. Tapped the stop button and the app said GPS accuracy was to low. So still an issue.

2. I tapped the iPhones home button. A while later when going back to the app the sequence had stopped and I was at the main menu of the app.

**Comment by jesolem** [comment]
Thanks @Andblue , I'll investigate. What version do you have?

**Comment by Andblue** [comment]
The latest iOS version on an iPhone 5S.

**Comment by millenbop** [comment]
Wasn't fixed, so fixed it now, will be available in next version.
