### ISSUE TITLE
Date stamps have been corrupted -  Jan 1, 1970

### ISSUE THREAD

**Issue by geomapper69** [mapillary/mapillary_issues#581]
http://www.mapillary.com/map/im/iySEloJtXNqY_e-bVeE5iw
![randon_sequence](https://cloud.githubusercontent.com/assets/10060476/6019644/57628dd8-abbc-11e4-8ab9-e4a66f3ef6dd.png)

A sequence of photos appear to be corrupted.
The sequence seems to be randomised and the dates have been reset to Jan 1, 1970.

They were uploaded with python - upload_with_authentication.py.
It is possible (but unlikely) that pictures from the wrong sequence have been mixed in the same folder.  I should be able to fix the sequences by using the cut if > 300m in the editor.  But I don't understand what has happened with the dates.

**Comment by ybkuang** [comment]
@geomapper69 This is due to a problem in the processing backend. We are working on fixing that now.

**Comment by lordsutch** [comment]
This looks like the same problem I'm having with a few recent traces (an upload that looks like an Etch-A-Sketch with everything jumbled up), although most of the timestamps appear to be correct (I think the timestamps show Unix Time 0 when they're still processing, which is a separate issue).

Example: http://www.mapillary.com/map/e/wL6idYBLZcGYDGybFSlQuQ

**Comment by ybkuang** [comment]
@lordsutch Yes. It is the same issue as above. We are reprocessing the images to correct this, which will take a while. Sorry about this.

**Comment by gyllen** [comment]
This should now be fixed. Please verify @geomapper69  and @lordsutch once again sorry for this guys.

**Comment by geomapper69** [comment]
fixed

**Comment by dymo** [comment]
I still have photos with Jan 1 1970 like this

http://www.mapillary.com/map/im/16MWZvHRaYJn62eiOP8CzQ

and this sequence still have a serious "spider web":

http://www.mapillary.com/map/im/B4TSNMHBEftxvguTY3zU9A

**Comment by geomapper69** [comment]
@dymo reopened issue due to your problems

**Comment by gyllen** [comment]
@dymo Both looks fine now, lag in system. Closing. Please reopen if you guys see more strange things.

**Comment by dymo** [comment]
@gyllen I'm not allowed to reopen since it is not my issue.

I still have the problem with these sequences:
http://www.mapillary.com/map/im/EY5VCDqkOgBGZHrNgDubMg
http://www.mapillary.com/map/im/CjsNowvpTPqsXW37GAHWyA
http://www.mapillary.com/map/im/3Phf6ri4hphXeHhMqLp8CQ
http://www.mapillary.com/map/im/RBhPkSAwNNxUHeSlN7Y0pg

at least one of them is more than a month old, so i suspect it is more than just normal lag.

**Comment by ybkuang** [comment]
Hi, @dymo.  We will take a look.

**Comment by lordsutch** [comment]
The "spiderweb" issue seems to be gone with the sequence I uploaded; however, forward and back clicks on pictures are jumping around the sequence rather than the adjacent pictures.

**Comment by gyllen** [comment]
@peterneubauer I think this depends on GS

**Comment by voschix** [comment]
I just detected two possibly related problems:
1) Some of my early sequences (manually uploaded GoPro photos) from November 2014 around Novigrad in Croatia have completely disappeared. I am pretty sure they were uploaded correctly, because I souwed them to friends to demonstrate the potential of Mapillary.
2) Others are damaged in the sense that the trace on the map is still correct, but many, but not all pictures of the sequnce have the above time stamp error and their position is not shown on the map (I presume they not only have the wrong date, but also lack the coordinate data, because, when I open the picture's URL, no map is shown  - 
example: http://www.mapillary.com/map/im/Qlj4XLq0aj2lD50gkxMHEQ)

**Comment by gyllen** [comment]
Hi @voschix 

Can you see your images on your profile page here http://www.mapillary.com/profile/voschix . Im sure the data is intact we just need to backtrace to see what happend.

**Comment by gyllen** [comment]
@peterneubauer Can you look into the timestamps. I double checked and they are in fact stored correct in the database.

**Comment by gyllen** [comment]
@voschix Are the the GoPro images you are looking for http://www.mapillary.com/map/im/75uz1GWkPdzHpuvBhkEkAQ ?

**Comment by peterneubauer** [comment]
Volker,
http://www.mapillary.com/map/im/Qlj4XLq0aj2lD50gkxMHEQ is now corrected, are there more of this sort so I can update them with a script?

**Comment by voschix** [comment]
The short answer is: there are many more, but I'm not sure if the script is
the right answer in this case.
I will send a detailed replay shortly via e-mail directly to Peter and
Johan.
Volker

**Comment by peterneubauer** [comment]
Yes,
I just want to find the pattern to search and correct on. Thanks Volker!

**Comment by dymo** [comment]
The sequences i linked to still have loops.
They are all uploaded with the Python script.

**Comment by SanderH** [comment]
I also see some of my uploads going wrong with the 1970 date. They're all Garmin VIRB images.
All uploaded with the upload_with_authentication.py script. Samples where it's going wrong:
http://www.mapillary.com/map/s/ZygCAndT7bKC6sO_NVkyKA
http://www.mapillary.com/map/s/Wor1jg6zhsbRdI_x5RFLxg
and an older one uploaded with the upload_each_folder_as_sequence.py script:
http://www.mapillary.com/map/s/BpXndESKuGbRZqoqUHRgMw
Some other seqences seem to have fixed themselves and it's not occurring always, but it's quite annoying when it happens.

**Comment by ybkuang** [comment]
@SanderH it is a glitch in our processing. It is fixed now. The system is currently reprocessing the sequences. The date of some sequence has been corrected http://www.mapillary.com/map/im/ZygCAndT7bKC6sO_NVkyKA.
