### ISSUE TITLE
Annoying spinner bug

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#697]
I found a quite annoying bug while editing traffic signs in map mode.

To reproduce:
- turn on traffic signs
- go to another photo
- after the photo, the buttons an the signs are loaded there is a mapillary-green spinner. (no idea what it's for)
- click, before this spinner is done on the new-sign-button.
- when the mapillary-green spinner disappears, so does the 'new sign red box'.
- the 'select traffic signs' box is still open, but choosing a sign is useless, because the red box is already gone.

**Comment by de-vries** [comment]
Click on the traffic sign icon (in the photo, or bottom left) of an existing sign, before this mapillary-green spinner is done and anything chosen in the 'select traffic signs' box has no effect.
Click on the trash icon, before this mapillary-green spinner is done and the sign returns when the spinner is done.

**Comment by gyllen** [comment]
Should now be fixed with new interface

**Comment by de-vries** [comment]
Although the green spinner is gone I can still reproduce it.
