### ISSUE TITLE
Select Traffic Signs not centered right

### ISSUE THREAD

**Issue by de-vries** [mapillary/mapillary_issues#725]
The "Select Traffic Signs" box is not centered right when you expand the score list.

1. click show all
2. list expands
3. open "Select Traffic Signs" box
4. box is so low I almost can't see the buttons

**Comment by knikel** [comment]
This has been fixed, will be visible soon.

**Comment by de-vries** [comment]
I'm still having this issue in FF. Only difference is that the "select traffic sign" box is now in a lightbox that prevent scrolling down. in chromium there is no problem.

I found that `.modal__content {top: 10%;}` isn't doing anything in chromium and causing the issue in FF. you might as well remove it. 
Only thing is that in FF `.modal__content {top: 10%;}` makes for a slightly better looking and more dynamic design.

**Comment by knikel** [comment]
I've pushed few fixes, the modal should behave slightly better now. Thanks!

**Comment by de-vries** [comment]
nice!
