### ISSUE TITLE
Sequence of rear view images on mapillary site

### ISSUE THREAD

**Issue by PeeWeeOSM** [mapillary/mapillary_issues#788]
I've taken some sequences  with the camera looking backward. Here's an example.
http://www.mapillary.com/map/im/-mlul1Zm-ZTVI4FFgDnqzw

I know these are taken looking backward but users of the website don't. They expect to go forward when they push the arrow that points up. Instead they go backward. The same goes for the "play" button.

**Comment by jesolem** [comment]
Good point. We should fix this.

**Comment by kaitu** [comment]
Playing in reverse might look funny with moving objects. For example an approaching car will be seen speeding backwards.

**Comment by PeeWeeOSM** [comment]
Yes it is funny and on top of that it  also looks like  I am riding on the wrong side of the road  ;)

**Comment by polarbearing** [comment]
Isn't that simply an issue of setting the viewing angle correctly, as discussed in #776 ?

**Comment by HolgerJeromin** [comment]
@polarbearing the viewing angle IS correct. Everything is ok, but the pictures have reversed timestamps. This is the source of the "next" arrows.

**Comment by pbb72** [comment]
People should be able to play a sequence in either direction. Most of my sequences are left or right side view. "Forward" and "backward" do no apply to those kind of sequences, you should be able to go either way.

**Comment by filipca** [comment]
People should be able to see where the beginning is.

**Comment by floscher** [comment]
> People should be able to play a sequence in either direction.

This can be seen as a special case of #744. When the play speed is configurable, you can simply set the speed to a negative value.

**Comment by ybkuang** [comment]
This has now been fixed with the new [release ](https://blog.mapillary.com/update/2017/12/11/mapillaryjs-sequence-playback-speed-direction.html). Thanks for the suggestions.

**Comment by PeeWeeOSM** [comment]
Hi  Yubin

If I look at this sequence and use the play function it still goes the
wrong way. So I don't think it is fixed.

https://www.mapillary.com/app/?lat=52.44880150003394&lng=9.92972975007524&z=19.68796007924884&focus=photo&pKey=iI2D0uP_N_Y8DPWa2WmaNA


2018-07-19 18:42 GMT+02:00 Yubin Kuang <notifications@github.com>:

**Comment by ybkuang** [comment]
@PeeWeeOSM You can actually now play the sequence backwards in time. With that, the direction will be ok. Take a look at the [blogpost](https://blog.mapillary.com/update/2017/12/11/mapillaryjs-sequence-playback-speed-direction.html).

**Comment by ybkuang** [comment]
![image](https://user-images.githubusercontent.com/5370656/42978458-37e23392-8bcd-11e8-83f4-99387ea0750b.png)

Click the rabbit, and choose the double arrows on the far left will enable reverse play order.
