### ISSUE TITLE
Traffic sign game should not show images you have already edited

### ISSUE THREAD

**Issue by smsm1** [mapillary/mapillary_issues#840]
After around 200 images, I'm starting to get images that I've previously edited. Can this be avoided? http://www.mapillary.com/map/games/traffic

**Comment by smsm1** [comment]
This is happening far too frequently, thus slowing me down, and getting annoying.

**Comment by smsm1** [comment]
I'm beginning to wonder if there's some filter to prevent me seeing any images that I've taken, whereas it should be filtering on whether I was the last editor of the detected signs?

**Comment by de-vries** [comment]
This is a known problem and according to https://github.com/mapillary/mapillary_issues/issues/673#issuecomment-77228759 it should be fixed.

**Comment by smsm1** [comment]
I've just tried it on another browser which I've not used for the game before and the 3rd photo was one which I was the last person to confirm, thus I believe the issue is still there.

**Comment by knikel** [comment]
Closing due to https://github.com/mapillary/mapillary_issues/issues/1618#issuecomment-184142118
