### ISSUE TITLE
Traffic signs icons are "blurred" at high zoom levels

### ISSUE THREAD

**Issue by pyrog** [mapillary/mapillary_issues#909]
![blured icons](https://cloud.githubusercontent.com/assets/2158081/7089915/929a8970-df9f-11e4-9fc2-10ed8c4eab28.png)

**Comment by knikel** [comment]
@pyrog which browser are you using?

**Comment by pyrog** [comment]
@knikel 
Safari Version 8.0.4 (10600.4.10.7)
Mac OS X 10.10.2

**Comment by iav** [comment]
Icons blurred only when roadsigns loads from mapilary. For photos cleanob start, then add roadsigns manually, icons are clear.

**Comment by pyrog** [comment]
Ok with Chrome Version 41.0.2272.118 (64-bit)

**Comment by pyrog** [comment]
Icons are also blurred on image view even with **Chrome** (fine with Firefox):
![icons blurred on image view](https://cloud.githubusercontent.com/assets/2158081/7100964/038196ac-e03f-11e4-81f5-334616e19090.png)
[ZGNtxeH7nWxOl6vu7x6B1w](http://www.mapillary.com/map/im/ZGNtxeH7nWxOl6vu7x6B1w)

**Comment by knikel** [comment]
@pyrog @iav This issue has been fixed. It was a font-smoothing problem. Thanks for reporting!

**Comment by pyrog** [comment]
Work fine after clearing the cache. Thanks :smile:

**Comment by pyrog** [comment]
Ooops, the bug is still there even after clearing the cache (in all views ?)
* Game view    
![blured sign game view](https://cloud.githubusercontent.com/assets/2158081/7301743/d93c7088-e9e4-11e4-9482-94bd086326de.png)
* Map view    
![blured sign map view](https://cloud.githubusercontent.com/assets/2158081/7301749/e0b89288-e9e4-11e4-8621-fc9a014c3d2f.png)
* Edit view ?? (Traffic signs are not displayed over the picture)

**Comment by knikel** [comment]
Won't be an issue after we update the viewer to use `mapillary-js`

**Comment by gyllen** [comment]
@oscarlorentzon Can you confirm this?

**Comment by oscarlorentzon** [comment]
There should not a need to zoom through the browser when mapillary/mapillary-js#112 and mapillary/mapillary-js#92 has been implemented which will solve this problem in practice. 

Also traffic sign icons will not get blurred like in the screenshots above, they are just regular images. Although it is not possible to increase the resolution of the sprites when zooming in the browser so a zoomed sprite will be a little bit blurry.

**Comment by gyllen** [comment]
@oscarlorentzon I assume not as blurry as above though. If its just a "little" blurry. Feel free to close this issue.

**Comment by oscarlorentzon** [comment]
Yes, just a little blurry as any image is when scaling it up.

**Comment by gyllen** [comment]
Ok closing then
